import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import "./globals.css";
import { getArticleList } from "./http";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  getArticleList();
  //  const data =await get('http://123.207.197.182:3000/api/article')
  //   console.log(typeof window,'========',data)

  return (
    <html lang="en">
      <body className={inter.className}>
      <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
